import test from 'node:test';import assert from 'node:assert/strict';import {configuration} from '../src/config.js';import {Tables} from '../src/player.js';import {Protocol} from '../src/protocol.js';import {Store} from '../src/store.js';import {Game} from '../src/game.js';import {grantRewards} from '../src/rewards.js';import {releaseLedger} from '../src/release-ledger.js';
const c=configuration(),t=new Tables(c.tables),p=new Protocol(c.base);
function setup(){let now=1800000000;const store=new Store(':memory:'),game=new Game(p,store,t,{clock:()=>now}),session={};let seq=1;const call=(name,r)=>{const e=p.byName.get('CSProto'+name);return game.dispatch(session,{id:e.id,seq:seq++,pushSeq:0,payload:p.encode(e.req,r)});};call('EnterGame',{open_id:'release'});return {store,session,call,advance:n=>{now+=n;}};}
test('pet release returns configured experience materials and deletion precedes response',()=>{const {store,session,call}=setup();try{
 const id=store.load(session.id).state.pets[0].guid;call('PetLock',{guid:id,lock_operate:false});store.transact(session.id,0,s=>{s.pets[0].lv=6;s.pets[0].exp=25;});const packets=call('DelPet',{pet_list:[id]});const reply=p.decode('Rewards',packets.find(x=>x.id===6512).payload);assert.deepEqual(reply.rewards.map(r=>[r.itemid,r.itemnum]),[[402000,1]]);assert(packets.findIndex(x=>x.id===6517)<packets.findIndex(x=>x.id===6512));const sync=p.decode('SCPetInfoSync',packets.find(x=>x.id===6517).payload);assert.deepEqual(sync.pet_infos.guid,[id]);assert.equal(sync.free_reward_num,0);assert(!store.load(session.id).state.pets.some(p=>p.guid===id));const before=store.load(session.id);assert.throws(()=>call('DelPet',{pet_list:[id]}));assert.deepEqual(store.load(session.id),before);
}finally{store.close();}});
test('daily bonus caps at 30 eligible releases and resets on a new server day',()=>{const {store,session,call,advance}=setup();try{
 const make=count=>store.transact(session.id,0,s=>{const rewards=grantRewards(t,s,[{itemtype:5,itemid:500001,itemnum:count}]);for(const r of rewards)s.pets.find(p=>p.guid===r.guid).is_lock=false;return rewards.map(r=>r.guid);});
 const ids=make(31);call('DelPet',{pet_list:ids});let s=store.load(session.id).state;assert.equal(s.releaseLedgers.pet.count,30);assert.equal(s.player.sbag_infos.items.find(i=>i.itemid===402000).itemnum,30);
 call('DelPet',{pet_list:make(1)});assert.equal(store.load(session.id).state.player.sbag_infos.items.find(i=>i.itemid===402000).itemnum,30);advance(86400);call('DelPet',{pet_list:make(1)});s=store.load(session.id).state;assert.equal(s.releaseLedgers.pet.count,1);assert.equal(s.player.sbag_infos.items.find(i=>i.itemid===402000).itemnum,31);
}finally{store.close();}});
test('locked, equipped, mounted, stationed and duplicate pet selections are atomic failures',()=>{const {store,session,call}=setup();try{
 const id=store.load(session.id).state.pets[0].guid;let before=store.load(session.id);assert.throws(()=>call('DelPet',{pet_list:[id]}),/locked/);assert.deepEqual(store.load(session.id),before);call('PetLock',{guid:id,lock_operate:false});
 for(const values of [{hero_id:'123'},{roulette_pos:1},{work_status:2},{can_not_release:true}]){store.transact(session.id,0,s=>Object.assign(s.pets[0],{hero_id:'0',roulette_pos:0,work_status:0,can_not_release:false},values));before=store.load(session.id);assert.throws(()=>call('DelPet',{pet_list:[id]}));assert.deepEqual(store.load(session.id),before);}
 before=store.load(session.id);assert.throws(()=>call('DelPet',{pet_list:[id,id]}));assert.deepEqual(store.load(session.id),before);
}finally{store.close();}});
test('egg release gives no configured bonus and refuses active or locked eggs',()=>{const {store,session,call}=setup();try{
 store.transact(session.id,0,s=>grantRewards(t,s,[{itemtype:14,itemid:40003007,itemnum:2}]));call('PetEggLock',{guid:'1',lock_operate:true});let before=store.load(session.id);assert.throws(()=>call('DelEgg',{egg_list:[1,2]}),/locked/);assert.deepEqual(store.load(session.id),before);call('PetEggLock',{guid:'1',lock_operate:false});store.transact(session.id,0,s=>{s.petEggs[0].hatch_build_guid=99;});before=store.load(session.id);assert.throws(()=>call('DelEgg',{egg_list:[1]}),/incubating/);assert.deepEqual(store.load(session.id),before);
 const result=call('DelEgg',{egg_list:[2]});assert.deepEqual(p.decode('Rewards',result.find(x=>x.id===6513).payload).rewards,[]);assert.deepEqual(p.decode('SCPetEggInfoSync',result.find(x=>x.id===6518).payload).egg_infos.guid,[2]);assert.equal(store.load(session.id).state.petEggs.length,1);
}finally{store.close();}});
test('release reset boundary is the configured UTC+8 hour',()=>{const boundary=Date.parse('2026-09-26T04:00:00+08:00')/1000,old=releaseLedger({},'pet',boundary-1,4);old.count=30;const state={releaseLedgers:{pet:old}};assert.equal(releaseLedger(state,'pet',boundary-1,4).count,30);assert.equal(releaseLedger(state,'pet',boundary,4).count,0);assert.throws(()=>releaseLedger({},'pet',boundary,NaN));});
