import test from 'node:test';import assert from 'node:assert/strict';
import {configuration} from '../src/config.js';import {Tables} from '../src/player.js';import {Store} from '../src/store.js';import {Protocol} from '../src/protocol.js';import {Game} from '../src/game.js';
const cfg=configuration(),tables=new Tables(cfg.tables),protocol=new Protocol(cfg.base);
test('actual prologue controller opens trial107001, supports combat and reconnect, then restores owned formation',()=>{
 const store=new Store(':memory:'),game=new Game(protocol,store,tables);let session={},seq=1;const call=(name,r={})=>{const e=protocol.byName.get('CSProto'+name);return game.dispatch(session,{id:e.id,seq:seq++,payload:protocol.encode(e.req,r)}).map(p=>({id:p.id,data:protocol.decode(protocol.byId.get(p.id).rsp,p.payload)}));};const state=()=>store.load(session.id).state;
 try{call('EnterGame',{open_id:'trial-test'});const original=structuredClone(state().player.group_mgrs[0]),owned=structuredClone(state().player.heros_info.heros);
 const request={open:true,force:true,trial_heros:[{id:107001,pos:-1}]},packets=call('TrialGroupChange',request);assert.equal(packets[0].id,5988);assert.equal(packets.at(-1).id,5987);let s=state();const hero=s.trialGroup.heroes[0];assert.equal(hero.conf_id,107001);assert.equal(hero.hero_lv,1);assert(hero.trail);assert(!owned.some(h=>h.guid===hero.guid));assert.equal(s.player.group_mgrs[0].cur_group,0);assert.equal(s.player.group_mgrs[0].groups.find(g=>g.id===0).control,hero.guid);assert.equal(s.player.group_mgrs[0].src,0);
 const oldControl=original.groups.find(g=>g.id===original.cur_group).control,position=structuredClone(s.world.pos);call('SwitchWorldGroupControl',{type:1,control:oldControl,pos:{},switch_type:56});call('SwitchGroupControlEnd',{uuid:oldControl});assert.equal(state().player.group_mgrs[0].groups.find(g=>g.id===0).control,hero.guid);assert.deepEqual(state().world.pos,position);
 const enemy=((4n<<56n)|10600101n).toString();const hit=call('BattleInfoReduce',{uint64_dic:[hero.guid,enemy],battle_info:[{hurt_info:{from_id:'1',tar_id:'2',hp_change:-10}}]});assert(hit.some(p=>p.id===10706));assert.equal(state().combat.entities[enemy].config_id,310624);assert.equal(state().combat.entities[enemy].hp,state().combat.entities[enemy].max_hp-10);
 const hp=s.player.heros_info.battle_infos.find(h=>h.hero_id===hero.guid).hp;call('BattleInfoReduce',{uint64_dic:[hero.guid],battle_info:[{hurt_info:{tar_id:'1',hp_change:-1}}]});assert.equal(state().player.heros_info.battle_infos.find(h=>h.hero_id===hero.guid).hp,hp-1);
 call('TrialGroupChange',request);assert.equal(state().trialGroup.previous_group,original.cur_group);session={};const login=call('EnterGame',{open_id:'trial-test'});assert(login.some(p=>p.id===5988));assert.equal(state().player.group_mgrs[0].cur_group,0);
 const before=state();assert.throws(()=>call('TrialGroupChange',{...request,trial_heros:[{id:20000,pos:0}]}),/active task/);assert.deepEqual(state(),before);
 call('TrialGroupChange',{open:false,force:true});s=state();assert.equal(s.player.group_mgrs[0].cur_group,original.cur_group);assert.deepEqual(s.player.group_mgrs[0].groups,original.groups);assert.deepEqual(s.player.heros_info.heros,owned);assert.equal(s.trialGroup,undefined);assert(!s.player.heros_info.battle_infos.some(h=>h.hero_id===hero.guid));
 call('TrialGroupChange',request);call('EnterWorldMap',{map_id:100,point_id:10045});assert.equal(state().trialGroup,undefined);assert.equal(state().player.group_mgrs[0].cur_group,original.cur_group);
 call('EnterWorldMap',{map_id:102,point_id:10201});call('TrialGroupChange',request);store.transact(session.id,0,s=>{s.tasks[0].nodes=[{node_id:63,node_values:[0],client_before:false,client_cond_after:[false]}];});session={};call('EnterGame',{open_id:'trial-test'});assert.equal(state().trialGroup,undefined);assert.equal(state().player.group_mgrs[0].cur_group,original.cur_group);
 }finally{store.close();}
});
