// Reconstructed from FileDescriptorSet. Keep the original .pb for exact options.
syntax = "proto2";
package google.protobuf;
option java_package = "com.google.protobuf";
option java_outer_classname = "DescriptorProtos";
option optimize_for = SPEED;
option go_package = "github.com/golang/protobuf/protoc-gen-go/descriptor;descriptor";
option cc_enable_arenas = true;
option objc_class_prefix = "GPB";
option csharp_namespace = "Google.Protobuf.Reflection";
message FileDescriptorSet {
  repeated .google.protobuf.FileDescriptorProto file = 1 [json_name = "file"];
}
message FileDescriptorProto {
  optional string name = 1 [json_name = "name"];
  optional string package = 2 [json_name = "package"];
  repeated string dependency = 3 [json_name = "dependency"];
  repeated int32 public_dependency = 10 [json_name = "publicDependency"];
  repeated int32 weak_dependency = 11 [json_name = "weakDependency"];
  repeated .google.protobuf.DescriptorProto message_type = 4 [json_name = "messageType"];
  repeated .google.protobuf.EnumDescriptorProto enum_type = 5 [json_name = "enumType"];
  repeated .google.protobuf.ServiceDescriptorProto service = 6 [json_name = "service"];
  repeated .google.protobuf.FieldDescriptorProto extension = 7 [json_name = "extension"];
  optional .google.protobuf.FileOptions options = 8 [json_name = "options"];
  optional .google.protobuf.SourceCodeInfo source_code_info = 9 [json_name = "sourceCodeInfo"];
  optional string syntax = 12 [json_name = "syntax"];
}
message DescriptorProto {
  message ExtensionRange {
    optional int32 start = 1 [json_name = "start"];
    optional int32 end = 2 [json_name = "end"];
    optional .google.protobuf.ExtensionRangeOptions options = 3 [json_name = "options"];
  }
  message ReservedRange {
    optional int32 start = 1 [json_name = "start"];
    optional int32 end = 2 [json_name = "end"];
  }
  optional string name = 1 [json_name = "name"];
  repeated .google.protobuf.FieldDescriptorProto field = 2 [json_name = "field"];
  repeated .google.protobuf.FieldDescriptorProto extension = 6 [json_name = "extension"];
  repeated .google.protobuf.DescriptorProto nested_type = 3 [json_name = "nestedType"];
  repeated .google.protobuf.EnumDescriptorProto enum_type = 4 [json_name = "enumType"];
  repeated .google.protobuf.DescriptorProto.ExtensionRange extension_range = 5 [json_name = "extensionRange"];
  repeated .google.protobuf.OneofDescriptorProto oneof_decl = 8 [json_name = "oneofDecl"];
  optional .google.protobuf.MessageOptions options = 7 [json_name = "options"];
  repeated .google.protobuf.DescriptorProto.ReservedRange reserved_range = 9 [json_name = "reservedRange"];
  repeated string reserved_name = 10 [json_name = "reservedName"];
}
message ExtensionRangeOptions {
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
}
message FieldDescriptorProto {
  enum Type {
    TYPE_DOUBLE = 1;
    TYPE_FLOAT = 2;
    TYPE_INT64 = 3;
    TYPE_UINT64 = 4;
    TYPE_INT32 = 5;
    TYPE_FIXED64 = 6;
    TYPE_FIXED32 = 7;
    TYPE_BOOL = 8;
    TYPE_STRING = 9;
    TYPE_GROUP = 10;
    TYPE_MESSAGE = 11;
    TYPE_BYTES = 12;
    TYPE_UINT32 = 13;
    TYPE_ENUM = 14;
    TYPE_SFIXED32 = 15;
    TYPE_SFIXED64 = 16;
    TYPE_SINT32 = 17;
    TYPE_SINT64 = 18;
  }
  enum Label {
    LABEL_OPTIONAL = 1;
    LABEL_REQUIRED = 2;
    LABEL_REPEATED = 3;
  }
  optional string name = 1 [json_name = "name"];
  optional int32 number = 3 [json_name = "number"];
  optional .google.protobuf.FieldDescriptorProto.Label label = 4 [json_name = "label"];
  optional .google.protobuf.FieldDescriptorProto.Type type = 5 [json_name = "type"];
  optional string type_name = 6 [json_name = "typeName"];
  optional string extendee = 2 [json_name = "extendee"];
  optional string default_value = 7 [json_name = "defaultValue"];
  optional int32 oneof_index = 9 [json_name = "oneofIndex"];
  optional string json_name = 10 [json_name = "jsonName"];
  optional .google.protobuf.FieldOptions options = 8 [json_name = "options"];
}
message OneofDescriptorProto {
  optional string name = 1 [json_name = "name"];
  optional .google.protobuf.OneofOptions options = 2 [json_name = "options"];
}
message EnumDescriptorProto {
  message EnumReservedRange {
    optional int32 start = 1 [json_name = "start"];
    optional int32 end = 2 [json_name = "end"];
  }
  optional string name = 1 [json_name = "name"];
  repeated .google.protobuf.EnumValueDescriptorProto value = 2 [json_name = "value"];
  optional .google.protobuf.EnumOptions options = 3 [json_name = "options"];
  repeated .google.protobuf.EnumDescriptorProto.EnumReservedRange reserved_range = 4 [json_name = "reservedRange"];
  repeated string reserved_name = 5 [json_name = "reservedName"];
}
message EnumValueDescriptorProto {
  optional string name = 1 [json_name = "name"];
  optional int32 number = 2 [json_name = "number"];
  optional .google.protobuf.EnumValueOptions options = 3 [json_name = "options"];
}
message ServiceDescriptorProto {
  optional string name = 1 [json_name = "name"];
  repeated .google.protobuf.MethodDescriptorProto method = 2 [json_name = "method"];
  optional .google.protobuf.ServiceOptions options = 3 [json_name = "options"];
}
message MethodDescriptorProto {
  optional string name = 1 [json_name = "name"];
  optional string input_type = 2 [json_name = "inputType"];
  optional string output_type = 3 [json_name = "outputType"];
  optional .google.protobuf.MethodOptions options = 4 [json_name = "options"];
  optional bool client_streaming = 5 [default = false, json_name = "clientStreaming"];
  optional bool server_streaming = 6 [default = false, json_name = "serverStreaming"];
}
message FileOptions {
  enum OptimizeMode {
    SPEED = 1;
    CODE_SIZE = 2;
    LITE_RUNTIME = 3;
  }
  optional string java_package = 1 [json_name = "javaPackage"];
  optional string java_outer_classname = 8 [json_name = "javaOuterClassname"];
  optional bool java_multiple_files = 10 [default = false, json_name = "javaMultipleFiles"];
  optional bool java_generate_equals_and_hash = 20 [deprecated = true, json_name = "javaGenerateEqualsAndHash"];
  optional bool java_string_check_utf8 = 27 [default = false, json_name = "javaStringCheckUtf8"];
  optional .google.protobuf.FileOptions.OptimizeMode optimize_for = 9 [default = SPEED, json_name = "optimizeFor"];
  optional string go_package = 11 [json_name = "goPackage"];
  optional bool cc_generic_services = 16 [default = false, json_name = "ccGenericServices"];
  optional bool java_generic_services = 17 [default = false, json_name = "javaGenericServices"];
  optional bool py_generic_services = 18 [default = false, json_name = "pyGenericServices"];
  optional bool php_generic_services = 42 [default = false, json_name = "phpGenericServices"];
  optional bool deprecated = 23 [default = false, json_name = "deprecated"];
  optional bool cc_enable_arenas = 31 [default = false, json_name = "ccEnableArenas"];
  optional string objc_class_prefix = 36 [json_name = "objcClassPrefix"];
  optional string csharp_namespace = 37 [json_name = "csharpNamespace"];
  optional string swift_prefix = 39 [json_name = "swiftPrefix"];
  optional string php_class_prefix = 40 [json_name = "phpClassPrefix"];
  optional string php_namespace = 41 [json_name = "phpNamespace"];
  optional string php_metadata_namespace = 44 [json_name = "phpMetadataNamespace"];
  optional string ruby_package = 45 [json_name = "rubyPackage"];
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
  reserved 38 to 38;
}
message MessageOptions {
  optional bool message_set_wire_format = 1 [default = false, json_name = "messageSetWireFormat"];
  optional bool no_standard_descriptor_accessor = 2 [default = false, json_name = "noStandardDescriptorAccessor"];
  optional bool deprecated = 3 [default = false, json_name = "deprecated"];
  optional bool map_entry = 7 [json_name = "mapEntry"];
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
  reserved 8 to 8;
  reserved 9 to 9;
}
message FieldOptions {
  enum CType {
    STRING = 0;
    CORD = 1;
    STRING_PIECE = 2;
  }
  enum JSType {
    JS_NORMAL = 0;
    JS_STRING = 1;
    JS_NUMBER = 2;
  }
  optional .google.protobuf.FieldOptions.CType ctype = 1 [default = STRING, json_name = "ctype"];
  optional bool packed = 2 [json_name = "packed"];
  optional .google.protobuf.FieldOptions.JSType jstype = 6 [default = JS_NORMAL, json_name = "jstype"];
  optional bool lazy = 5 [default = false, json_name = "lazy"];
  optional bool deprecated = 3 [default = false, json_name = "deprecated"];
  optional bool weak = 10 [default = false, json_name = "weak"];
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
  reserved 4 to 4;
}
message OneofOptions {
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
}
message EnumOptions {
  optional bool allow_alias = 2 [json_name = "allowAlias"];
  optional bool deprecated = 3 [default = false, json_name = "deprecated"];
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
  reserved 5 to 5;
}
message EnumValueOptions {
  optional bool deprecated = 1 [default = false, json_name = "deprecated"];
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
}
message ServiceOptions {
  optional bool deprecated = 33 [default = false, json_name = "deprecated"];
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
}
message MethodOptions {
  enum IdempotencyLevel {
    IDEMPOTENCY_UNKNOWN = 0;
    NO_SIDE_EFFECTS = 1;
    IDEMPOTENT = 2;
  }
  optional bool deprecated = 33 [default = false, json_name = "deprecated"];
  optional .google.protobuf.MethodOptions.IdempotencyLevel idempotency_level = 34 [default = IDEMPOTENCY_UNKNOWN, json_name = "idempotencyLevel"];
  repeated .google.protobuf.UninterpretedOption uninterpreted_option = 999 [json_name = "uninterpretedOption"];
  extensions 1000 to max;
}
message UninterpretedOption {
  message NamePart {
    required string name_part = 1 [json_name = "namePart"];
    required bool is_extension = 2 [json_name = "isExtension"];
  }
  repeated .google.protobuf.UninterpretedOption.NamePart name = 2 [json_name = "name"];
  optional string identifier_value = 3 [json_name = "identifierValue"];
  optional uint64 positive_int_value = 4 [json_name = "positiveIntValue"];
  optional int64 negative_int_value = 5 [json_name = "negativeIntValue"];
  optional double double_value = 6 [json_name = "doubleValue"];
  optional bytes string_value = 7 [json_name = "stringValue"];
  optional string aggregate_value = 8 [json_name = "aggregateValue"];
}
message SourceCodeInfo {
  message Location {
    repeated int32 path = 1 [packed = true, json_name = "path"];
    repeated int32 span = 2 [packed = true, json_name = "span"];
    optional string leading_comments = 3 [json_name = "leadingComments"];
    optional string trailing_comments = 4 [json_name = "trailingComments"];
    repeated string leading_detached_comments = 6 [json_name = "leadingDetachedComments"];
  }
  repeated .google.protobuf.SourceCodeInfo.Location location = 1 [json_name = "location"];
}
message GeneratedCodeInfo {
  message Annotation {
    repeated int32 path = 1 [packed = true, json_name = "path"];
    optional string source_file = 2 [json_name = "sourceFile"];
    optional int32 begin = 3 [json_name = "begin"];
    optional int32 end = 4 [json_name = "end"];
  }
  repeated .google.protobuf.GeneratedCodeInfo.Annotation annotation = 1 [json_name = "annotation"];
}
